// Generated by CoffeeScript 1.3.3
(function() {
  var CumulativeFlow, cradle;

  cradle = require('cradle');

  CumulativeFlow = (function() {

    function CumulativeFlow() {
      this.connect = new cradle.Connection({
        host: 'https://docondev.cloudant.com',
        cache: true,
        raw: false,
        port: 443,
        secure: true,
        auth: {
          username: "docondev",
          password: "Agil3cloud"
        }
      });
      this.db = this.connect.database('playground');
    }

    CumulativeFlow.prototype.findAll = function(callback) {
      return this.db.view('points/all', {
        descending: false
      }, function(err, res) {
        var records;
        if (err) {
          console.log(err);
          return callback(err);
        } else {
          records = [];
          res.forEach(function(row) {
            row.date = new Date(row.date);
            return records.push(row);
          });
          return callback(null, records);
        }
      });
    };

    return CumulativeFlow;

  })();

  exports.CumulativeFlow = CumulativeFlow;

}).call(this);
